device: 0
exp_name: 'scipad'
dataset:
  name: kitti
  data_path: 'kitti_data/kitti_raw'
train:
  epochs: 30
  batch_size: 8
  lr: 1e-4
  num_workers: 20
stunet:
  backbone: 'resnet18'
teanet:
  backbone: 'resnet18'
posenet:
  version: 'PoseNet'
  backbone: 'resnet18'
