device: 0
exp_name: 'tridepth_baseline'
dataset:
  name: kitti
  data_path: '/home/fengyi/datasets/kitti_mono2'
train:
  epochs: 30
  batch_size: 12
  lr: 1e-4
  num_workers: 20
stunet:
  backbone: 'resnet18'
teanet:
  backbone: 'resnet18'
posenet:
  backbone: 'resnet18'
